[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
web3_sol_program = "CoEMzqqpFTuzofY6Qxv993dXX8tbzBEJZDYzFinXphz2"

[programs.devnet]
web3_sol_program = "CoEMzqqpFTuzofY6Qxv993dXX8tbzBEJZDYzFinXphz2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/web3-sol-program.js -p 3030"
